# Generated by Django 5.1.7 on 2025-03-20 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('drone_ops_nb', models.CharField(blank=True, max_length=100, null=True)),
                ('pilot_license_nb', models.CharField(blank=True, max_length=100, null=True)),
                ('a1_a3', models.DateField(blank=True, null=True)),
                ('a2', models.DateField(blank=True, null=True)),
                ('sts', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UAV',
            fields=[
                ('uav_id', models.AutoField(primary_key=True, serialize=False)),
                ('drone_name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('motors', models.IntegerField()),
                ('motor_type', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('video_system', models.CharField(blank=True, max_length=255, null=True)),
                ('esc', models.CharField(blank=True, max_length=100, null=True)),
                ('esc_firmware', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_firmware', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_controller', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=100, null=True)),
                ('gps', models.CharField(blank=True, max_length=100, null=True)),
                ('mag', models.CharField(blank=True, max_length=100, null=True)),
                ('baro', models.CharField(blank=True, max_length=100, null=True)),
                ('gyro', models.CharField(blank=True, max_length=100, null=True)),
                ('acc', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('custom_attributes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uavs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceReminder',
            fields=[
                ('reminder_id', models.AutoField(primary_key=True, serialize=False)),
                ('component', models.CharField(max_length=100)),
                ('last_maintenance', models.DateTimeField()),
                ('next_maintenance', models.DateTimeField()),
                ('reminder_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reminders', to='api.uav')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to=settings.AUTH_USER_MODEL)),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='api.uav')),
            ],
        ),
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('flightlog_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_place', models.CharField(max_length=255)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('landing_place', models.CharField(max_length=255)),
                ('landing_time', models.TimeField()),
                ('flight_duration', models.IntegerField()),
                ('takeoffs', models.IntegerField()),
                ('landings', models.IntegerField()),
                ('light_conditions', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], max_length=255)),
                ('ops_conditions', models.CharField(choices=[('VLOS', 'VLOS'), ('BLOS', 'BLOS')], max_length=255)),
                ('pilot_type', models.CharField(choices=[('PIC', 'PIC'), ('Dual', 'Dual'), ('Instruction', 'Instruction')], max_length=255)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flightlogs', to=settings.AUTH_USER_MODEL)),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flightlogs', to='api.uav')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.uav')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('settings_id', models.AutoField(primary_key=True, serialize=False)),
                ('preferred_units', models.CharField(blank=True, max_length=50, null=True)),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
