# Generated by Django 5.1.7 on 2025-05-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='uav',
            constraint=models.UniqueConstraint(fields=('user', 'drone_name'), name='unique_user_drone_name'),
        ),
    ]
