# Generated by Django 5.1.7 on 2025-05-17 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancereminder',
            name='component',
            field=models.CharField(choices=[('MOTOR', 'Motor'), ('PROPELLER', 'Propeller'), ('FRAME', 'Frame')], max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenancereminder',
            name='last_maintenance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='maintenancereminder',
            name='next_maintenance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='maintenancereminder',
            name='uav',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='api.uav'),
        ),
        migrations.AddConstraint(
            model_name='maintenancereminder',
            constraint=models.UniqueConstraint(fields=('uav', 'component'), name='unique_uav_component_reminder'),
        ),
    ]
