# Generated by Django 5.1.7 on 2025-04-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_uav_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
