# Generated by Django 5.1.7 on 2025-04-20 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usersettings_a1_a3_reminder_usersettings_a2_reminder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightGPSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('num_sat', models.IntegerField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('ground_course', models.FloatField(blank=True, null=True)),
                ('flight_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_logs', to='api.flightlog')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
