services:
  db:
    image: postgres:17.4-bookworm
    restart: always
    environment:
      POSTGRES_USER: uav_manager
      POSTGRES_PASSWORD: DVgt8pf4
      POSTGRES_DB: uav_manager_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@carvalhais.ch
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_NAME=uav_manager_db
      - POSTGRES_USER=uav_manager
      - POSTGRES_PASSWORD=DVgt8pf4
      - POSTGRES_HOST=db
      - FRONTEND_URL=http://${API_HOST}:5175
      - ALLOWED_HOSTS=${API_HOST},localhost,127.0.0.1
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - VITE_API_URL=${API_URL}
    restart: always
    ports:
      - "5175:5175"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${API_URL}

volumes:
  postgres_data:
  pgadmin_data:
